name: arabicner
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=h27087fc_1
  - absl-py=1.3.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py310h5764c6d_1
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - arrow-cpp=8.0.0=py310h3098874_0
  - async-timeout=4.0.2=py310h06a4308_0
  - attrs=22.1.0=pyh71513ae_1
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - blas=1.0=mkl
  - blinker=1.5=pyhd8ed1ab_0
  - boost-cpp=1.78.0=he72f1d9_0
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.24=ha878542_0
  - cachetools=5.2.0=pyhd8ed1ab_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py310h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cryptography=38.0.1=py310h9ce1e76_0
  - cuda=11.7.1=0
  - cuda-cccl=11.7.91=0
  - cuda-command-line-tools=11.7.1=0
  - cuda-compiler=11.7.1=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cuobjdump=11.7.91=0
  - cuda-cupti=11.7.101=0
  - cuda-cuxxfilt=11.7.91=0
  - cuda-demo-suite=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.7.99=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.7.99=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.7.91=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.7.91=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-nvvp=11.8.87=0
  - cuda-runtime=11.7.1=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.7.1=0
  - cuda-tools=11.7.1=0
  - cuda-visual-tools=11.7.1=0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.6.1=pyhd8ed1ab_0
  - dill=0.3.5.1=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_h77c792f_102
  - filelock=3.8.0=pyhd8ed1ab_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.2.0=py310h7f8727e_1
  - fsspec=2022.10.0=pyhd8ed1ab_0
  - gds-tools=1.4.0.31=0
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h7b6447c_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.14.0=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpc-cpp=1.46.1=h33aed49_0
  - grpcio=1.42.0=py310hce63b2e_0
  - huggingface_hub=0.10.1=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.4=py310h06a4308_0
  - importlib-metadata=5.0.0=pyha770c72_1
  - importlib_metadata=5.0.0=hd8ed1ab_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h7f8727e_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcurl=7.85.0=h91b91d3_0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.20.1=h4ff587b_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libthrift=0.15.0=he6d91bd_0
  - libtiff=4.4.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h5764c6d_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - multidict=6.0.2=py310h5764c6d_1
  - multiprocess=0.70.12.2=py310h5764c6d_2
  - natsort=7.1.1=pyhd3eb1b0_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2022.3.0.22=0
  - numexpr=2.8.3=py310hcea2de6_0
  - numpy=1.23.3=py310hd5efca6_0
  - numpy-base=1.23.3=py310h8e6c178_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h7f8727e_0
  - orc=1.7.4=h07ed6aa_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.4=py310h6a678d5_0
  - pillow=9.2.0=py310hace64e9_1
  - pip=22.2.2=py310h06a4308_0
  - protobuf=3.20.1=py310hd8f1fbe_0
  - pyarrow=8.0.0=py310h468efa6_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.6=haa1d7c7_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-xxhash=3.0.0=py310h5764c6d_1
  - python_abi=3.10=2_cp310
  - pytorch=1.13.0=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h67b0de4_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.6=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5764c6d_4
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - regex=2022.7.9=py310h5eee18b_0
  - requests=2.28.1=py310h06a4308_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - responses=0.18.0=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - scikit-learn=1.1.3=py310h6a678d5_0
  - scipy=1.9.3=py310hd5efca6_0
  - seqeval=1.2.2=pyhd3deb0d_0
  - setuptools=65.4.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=hbd366e4_1
  - sqlite=3.39.3=h5082296_0
  - tensorboard=2.10.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py310h597c629_2
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h1ccaba5_0
  - tokenizers=0.11.4=py310h3dcd8bd_1
  - torchaudio=0.13.0=py310_cu117
  - torchtext=0.14.0=py310
  - torchvision=0.14.0=py310_cu117
  - tqdm=4.64.1=py310h06a4308_0
  - transformers=4.24.0=pyhd8ed1ab_0
  - typing-extensions=4.3.0=py310h06a4308_0
  - typing_extensions=4.3.0=py310h06a4308_0
  - tzdata=2022e=h04d1e81_0
  - urllib3=1.26.12=py310h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xxhash=0.8.0=h7f98852_3
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py310h5764c6d_2
  - zipp=3.10.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
prefix: /home/mkhalilia/.conda/envs/arabicner
